# @file
# .travis.yml - Drupal 8 Travis CI Integration

language: php

php:
  - 5.6
  - 7

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  - PATH="$HOME/.composer/vendor/bin:$PATH"

before_install:
  # possibly optional
  - sudo apt-get update > /dev/null
  - composer self-update
  - composer global require drush/drush

install:

  # Install Drupal 8.
  - cd ..
  - composer create-project drupal-composer/drupal-project:8.x drupal --stability dev --no-interaction

  # Create MySQL Database
  - mysql -e 'create database drupal;'

  - mv restrict drupal/web/modules
  - cd drupal/web

  # Install drupal default profile
  - drush --verbose site-install --db-url=mysql://root:@127.0.0.1/drupal --yes
  - drush en -y restrict
  - drush rs 8080 - &
  - cd ../

  # Ensure that the server is running.
  - sleep 5s

# only test our module tests
script: SIMPLETEST_BASE_URL=http://127.0.0.1:8080 SIMPLETEST_DB=mysql://root:@127.0.0.1/drupal drupal/vendor/bin/phpunit --group restrict --configuration drupal/web/core/phpunit.xml.dist
